Sprint 4
gitkh1/praktikum pull request #6
Opened 2022-11-30 14:14 UTC by gitkh1

2022-11-30 18:35 UTC, maks88sgt requested changes
Привет. Отличная работа! У тебя отлично получилась разбивка на модули, работа с тайпскриптом. Все критерии спринта закрыты, и не возникло никаких вопросов по ним. Предлагаю перед тем как идти дальше почистить код от комментариев и пофиксить баг, связанный с логикой работы вебсокетов.
Шаги, чтобы воспроизвести баг:
1. Открыть два браузера и авторизоваться под разными аккаунтами.
2. Подсоединиться к общему чату.
3. Одним из пользователей переключиться на другой чат.
4. Вторым пользователем отправить в общий чат сообщение.
5. Первым пользователем вернуться к общему чату.
6. Сообщение не будет доставлено адресату.
7. На стороне отправителя появиться сообщение с id адресата и NaN!NaN! вместо времени.
<img width="922" alt="image" src="https://user-images.githubusercontent.com/49103217/204879969-26cc2e93-bf5f-440f-88df-9a2fb0b4b774.png">
8. Затем если пользователь будет переключаться между чатами отправитель будет получать это сообщение снова и снова.

2022-11-30 18:35 UTC, maks88sgt commented on src/api/ws-api.ts
> +  // }
Закомментированный код лучше сразу удалять. В нем как правило нет ничего полезного, только снижает читаемость кода.

2022-11-30 19:08 UTC, maks88sgt commented
И еще один момент. Твоя работа очень похожа на https://github.com/jacksonrr3/middle.messenger.praktikum.yandex. Надеюсь ты помнишь о том, что по условиям курса плагиатом заниматься нельзя.

2022-12-01 00:02 UTC, gitkh1 commented on src/pages/Messeneger/Messenger.ts
> +    console.log('first')
Удалил

2022-12-01 00:02 UTC, gitkh1 commented on src/api/ws-api.ts
> +  // }
Удалил

2022-12-01 00:05 UTC, gitkh1 commented
> Привет. Отличная работа! У тебя отлично получилась разбивка на модули, работа с тайпскриптом. Все критерии спринта закрыты, и не возникло никаких вопросов по ним. Предлагаю перед тем как идти дальше почистить код от комментариев и пофиксить баг, связанный с логикой работы вебсокетов. Шаги, чтобы воспроизвести баг:
> 
> 1. Открыть два браузера и авторизоваться под разными аккаунтами.
> 2. Подсоединиться к общему чату.
> 3. Одним из пользователей переключиться на другой чат.
> 4. Вторым пользователем отправить в общий чат сообщение.
> 5. Первым пользователем вернуться к общему чату.
> 6. Сообщение не будет доставлено адресату.
> 7. На стороне отправителя появиться сообщение с id адресата и NaN!NaN! вместо времени.
> 
> <img alt="image" width="922" src="https://user-images.githubusercontent.com/49103217/204879969-26cc2e93-bf5f-440f-88df-9a2fb0b4b774.png">
> 
> 8. Затем если пользователь будет переключаться между чатами отправитель будет получать это сообщение снова и снова.

Не согласен с этим. Возможно, ты смотришь другую работу. У меня дизайн другой. Я проделал это на ВМ http://158.160.34.69/ такого не происходит, тем более от NaN там стоит защита в функции getTime

2022-12-01 00:09 UTC, gitkh1 commented
> ### **[maks88sgt](/maks88sgt) ** commented [Dec 1, 2022](#issuecomment-1332611739)

Это вообще не обосновано. Архитектура, код, дизайн, шаблонизатор (я вообще пользуюсь своим), или где?
Я бегло посмотрел эту работу и похожего ничего не нашел.

2022-12-01 02:28 UTC, maks88sgt commented
Привет. Извиняюсь. Действительно я перепутал докер контейнеры с приложением. У тебя отличная работа и вообще нет никаких вопросов. Работу принял. Успехов на курсе.

2022-12-01 03:15 UTC, merged